name = "Starfell - RoTVK"
author = "IvqryDev, NineRavens, Apenaz, SociopathicFungusGirl, Noelledotjpg, pinkman_worm13, and Many More Contributors"
version = "0.3-BETA"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a44c5758b086c606667972f4cec5c2bb4aa2211bdb1589366994adbbb9f8f2ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
