name = "Starfell - RoTVK"
author = "IvqryDev, NineRavens, Apenaz, SociopathicFungusGirl, Noelledotjpg, pinkman_worm13, and Many More Contributors"
version = "0.3-BETA"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2624fafd243207868cf3ffbb1d42694947b97cf09cd4b313469c3e21b8eea3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
