matchBlocks=mossy_stone_bricks mossy_stone_brick_stairs mossy_stone_brick_slab
method=random
biomes=ocean deep_ocean cold_ocean deep_cold_ocean deep_frozen_ocean frozen_ocean  river lukewarm_ocean deep_lukewarm_ocean warm_ocean deep_warm_ocean
tiles=mossy_stone_bricks
heights=61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45
weights=1
connect=block
animation=4
faces=top
