matchBlocks=prismarine_bricks
method=random
biomes=ocean deep_ocean cold_ocean deep_cold_ocean deep_frozen_ocean frozen_ocean  river lukewarm_ocean deep_lukewarm_ocean warm_ocean deep_warm_ocean
tiles=prismarine_bricks2
heights=51 50 49 48 47 46 45 44 43 42 41 40
weights=1
connect=block
animation=4
faces=top