matchBlocks=spruce_planks spruce_slab spruce_stairs spruce_fence
method=random
biomes=ocean deep_ocean cold_ocean deep_cold_ocean deep_frozen_ocean frozen_ocean  river lukewarm_ocean deep_lukewarm_ocean warm_ocean deep_warm_ocean
tiles=spruce_planks
heights=61 60 59 58 57 56 55 54 53 52
weights=1
connect=block
animation=4
faces=top
