ItemEvents.modification(event => {
	function stackTo64(x) {
		event.modify(x, item => {item.maxStackSize = 64})
	}
	function stackTo16(x) {
		event.modify(x, item => {item.maxStackSize = 16})
	}
	function stackTo4(x) {
		event.modify(x, item => {item.maxStackSize = 4})
	}

	//Combat Edibles
	stackTo4('minecraft:enchanted_golden_apple')
	stackTo16('minecraft:golden_apple')

	//Potions
	stackTo64('minecraft:potion')
	stackTo64('minecraft:splash_potion')
	stackTo64('minecraft:lingering_potion')

	//Placeable Foods
	stackTo16('minecraft:cake')
	stackTo16('minecraft:pumpkin_pie')
	stackTo16('farmersdelight:apple_pie')
	stackTo16('farmersdelight:sweet_berry_cheesecake')
	stackTo16('farmersdelight:chocolate_pie')
	stackTo16('brewinandchewin:quiche')
	stackTo16('brewinandchewin:pizza')
	stackTo16('farmersdelight:stuffed_pumpkin_block')
	stackTo16('farmersdelight:roast_chicken_block')
	stackTo16('farmersdelight:honey_glazed_ham_block')
	stackTo16('farmersdelight:shepherds_pie_block')
	stackTo16('farmersdelight:rice_roll_medley_block')
	stackTo16('mynethersdelight:striderloaf')
	stackTo16('mynethersdelight:ghasta_with_cream')

	//Items
	stackTo16('minecraft:dragon_breath')
	stackTo16('minecraft:minecart')
	stackTo16('minecraft:chest_minecart')
	stackTo16('minecraft:furnace_minecart')
	stackTo16('minecraft:tnt_minecart')
	stackTo16('minecraft:hopper_minecart')
	stackTo16('minecraft:command_block_minecart')
	stackTo16('supplementaries:dispenser_minecart')
	stackTo16('supplementaries:altimeter')
	stackTo16('minecraft:white_bed')
	stackTo16('minecraft:orange_bed')
	stackTo16('minecraft:magenta_bed')
	stackTo16('minecraft:light_blue_bed')
	stackTo16('minecraft:yellow_bed')
	stackTo16('minecraft:lime_bed')
	stackTo16('minecraft:pink_bed')
	stackTo16('minecraft:gray_bed')
	stackTo16('minecraft:light_gray_bed')
	stackTo16('minecraft:cyan_bed')
	stackTo16('minecraft:purple_bed')
	stackTo16('minecraft:blue_bed')
	stackTo16('minecraft:brown_bed')
	stackTo16('minecraft:green_bed')
	stackTo16('minecraft:red_bed')
	stackTo16('minecraft:black_bed')
	stackTo16('minecraft:saddle')
	stackTo16('minecraft:music_disc_13')
	stackTo16('minecraft:music_disc_cat')
	stackTo16('minecraft:music_disc_blocks')
	stackTo16('minecraft:music_disc_chirp')
	stackTo16('minecraft:music_disc_far')
	stackTo16('minecraft:music_disc_mall')
	stackTo16('minecraft:music_disc_mellohi')
	stackTo16('minecraft:music_disc_stal')
	stackTo16('minecraft:music_disc_strad')
	stackTo16('minecraft:music_disc_ward')
	stackTo16('minecraft:music_disc_11')
	stackTo16('minecraft:music_disc_wait')
	stackTo16('minecraft:music_disc_otherside')
	stackTo16('minecraft:music_disc_5')
	stackTo16('minecraft:music_disc_pigstep')
	stackTo16('minecraft:music_disc_creator_music_box')
	stackTo16('minecraft:music_disc_creator')
	stackTo16('minecraft:music_disc_precipice')
	stackTo16('minecraft:music_disc_relic')
	stackTo16('valcon:star_taker_music_disc')
	stackTo16('valcon:devil_trigger_music_disc')
	stackTo64('minecraft:snowball')
	stackTo64('minecraft:egg')
	stackTo64('farmersdelight:rotten_tomato')
	stackTo64('nomansland:incendiary_arrow')
	stackTo16('quark:ancient_tome')
})