#Allowed Values: FIRST, MIDDLE, LAST
weaponCoolDownImportance = "MIDDLE"
disablePickaxesAndShovels = false
disableAxes = false
showBlockBreaking = true
showRangeWeaponDraw = true
showItemCooldowns = false
showFoodAndPotions = false
showSleep = false
showItemContainerFullness = false
