		[types.wood_type.caverns_and_chasms]
			azalea = false

		[types.wood_type.quark]
			azalea = false
			ancient = false
			blossom = false

		[types.wood_type.upgrade_aquatic]
			driftwood = false
			river = false

		[types.wood_type.newworld]
			fir = true

		[types.wood_type.nomansland]
			pine = true
			maple = true
			walnut = true
			willow = true

		[types.wood_type.minecraft]
			pale_oak = true

		[types.wood_type.windswept]
			holly = true
			chestnut = true
			pine = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.leaves_type.quark]
			orange_blossom = false
			lavender_blossom = false
			ancient = false
			red_blossom = false
			blue_blossom = false
			yellow_blossom = false

		[types.leaves_type.upgrade_aquatic]
			river = false

		[types.leaves_type.newworld]
			fir = true

		[types.leaves_type.nomansland]
			yellow_birch = true
			autumnal_oak = true
			pale_cherry = true
			frosted = true
			pine = true
			maple = true
			red_maple = true
			walnut = true
			willow = true
			apple_fruit = true
			pear_fruit = true

		[types.leaves_type.minecraft]
			pale_oak = true

		[types.leaves_type.cookscollection]
			lemon = true
			fruiting_lemon = true

		[types.leaves_type.windswept]
			holly = true
			chestnut = true
			pine = true
			flowering_acacia = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.cake.nomansland]
			fruit_cake = true

		[types.lantern.caverns_and_chasms]
			cupric_lantern = true
			copper_lantern = true
			exposed_copper_lantern = true
			weathered_copper_lantern = true
			oxidized_copper_lantern = true
			waxed_copper_lantern = true
			waxed_exposed_copper_lantern = true
			waxed_weathered_copper_lantern = true
			waxed_oxidized_copper_lantern = true

		[types.lantern.windswept]
			ice_lantern = true

		[entries.wood_type.quark]
			ladder = false
			stripped_post = false
			chest = false
			bookshelf = false
			vertical_slab = false
			vertical_planks = false
			trapped_chest = false
			hollow_log = false
			post = false

		[entries.wood_type.another_furniture]
			flower_box = false
			table = true
			shelf = true
			drawer = true
			shutter = true
			bench = true
			chair = true

		[entries.wood_type.nomansland]
			bookshelf = true
			trimmed_planks = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true
