#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jul 08 06:52:32 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=Complementary Unbound.zip
