#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 19 01:25:58 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=Complementary Unbound.zip
