#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jun 23 08:13:57 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=Complementary Unbound.zip
